<?php
/**
 * PhpStorm
 *
 * @user LMG
 * @date 2020/8/28
 */


namespace app\api\controller;

/**
 * 需要登录的继承
 * @package app\api\controller
 */
class AuthBase extends ApiBase
{
    
    public $userId      = 0;
    
    public $username    = "";
    
    public $accessToken = '';
    
    /**
     * 初始化
     *
     * @user LMG
     * @date 2020/8/28
     */
    public function initialize()
    {
        
        parent ::initialize(); // TODO: Change the autogenerated stub
        $this -> accessToken = $this -> request -> header('access_token');
        if(!$this->accessToken||!$this -> isLogin()){
            return $this->showData(config('status.not_login'),'未登录！');
        }
    }
    
    /**
     * 是否登楼
     * @user LMG
     * @date 2020/8/28
     */
    public function isLogin()
    {
        
        $userInfo = cache(config('redis.token_pre').$this -> accessToken);
        if ( ! $userInfo) {
            return false;
        }
        if ( ! empty($userInfo[ 'id' ]) && ! empty($userInfo[ 'username' ])) {
            $this->userId=$userInfo['id'];
            $this->username=$userInfo['username'];
            return true;
        }
    }
    
}